# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://MeherKharbachi.github.io/football_graphs/"

git_url = "https://github.com/MeherKharbachi/football_graphs/tree/master/"

def custom_doc_links(name): return None
